sync-infrastructure:
  extends: .aws_base
  stage: infra
  script:
    - echo "Оновлюємо базову інфраструктуру..."
    - aws cloudformation deploy --stack-name mvp-infra-base --template-file infrastructure.yaml --no-fail-on-empty-changeset
    - echo "Оновлюємо обчислювальний шар..."
    - aws cloudformation deploy --stack-name mvp-compute-layer --template-file compute.yaml --parameter-overrides BaseStackName=mvp-infra-base --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
  only:
    changes:
      - infrastructure.yaml
      - compute.yaml
