stages:
  - infra
  - build
  - deploy-stage
  - deploy-prod

variables:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: "mvp-launcher-repo"
  ECS_CLUSTER: "mvp-launcher-cluster"
  AWS_DEFAULT_REGION: "us-east-1"

# Base AWS configuration inherited by other jobs
.aws_base:
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  before_script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION

# Include isolated pipeline modules
include:
  - local: "/.gitlab/ci-infra.yml"
  - local: "/.gitlab/ci-app.yml"
